name: "Sphinx: render docs"

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install Dependencies
      run: |
        pip install numpy
        pip install pandas
        pip install geopy
        pip install sphinx
        pip install nbsphinx

    - name: Build sphinx
      run: |
        sphinx-build -b docs/html docs/source docs/build