name: "Sphinx: render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: directly build sphinx
      run: |
        pip install -r requirements.txt
        sphinx-build -b html source build